# 🚀 bizinder-rag-engine Agent - Unified Docker Compose
# 7 Services: Agent UI, Agent API, bizinder-rag-engine API, PostgreSQL, Neo4j, MCP Server

services:
  # =================== DATABASE SERVICES ===================
  
  pgvector:
    build:
      context: .
      dockerfile: postgres.dockerfile
    container_name: bizinder-rag-engine-postgres
    restart: unless-stopped
    image: bizinder-rag-engine-postgres:18-pgvector
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/docker
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ai}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ai}
      POSTGRES_DB: ${POSTGRES_DATABASE:-ai}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    networks:
      - bizinder-rag-engine-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-ai} -d ${POSTGRES_DATABASE:-ai}"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  neo4j:
    image: neo4j:latest
    container_name: bizinder-rag-engine-neo4j
    restart: unless-stopped
    ports:
      - "7688:7687"  # Bolt protocol
      - "7475:7474"  # HTTP interface
    environment:
      NEO4J_AUTH: "neo4j/${NEO4J_PASSWORD:-biznder-test}"
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_connector_bolt_listen__address: "0.0.0.0:7687"
      NEO4J_dbms_connector_http_listen__address: "0.0.0.0:7474"
      NEO4J_dbms_memory_heap_initial__size: "512m"
      NEO4J_dbms_memory_heap_max__size: "1G"
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-import:/var/lib/neo4j/import
      - neo4j-plugins:/plugins
    networks:
      - bizinder-rag-engine-network
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p ${NEO4J_PASSWORD:-biznder-test} 'RETURN 1'"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


networks:
  bizinder-rag-engine-network:
    driver: bridge
    name: bizinder-rag-engine-network
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16

# =================== VOLUMES ===================

volumes:
  pgdata:
    driver: local
    name: bizinder-rag-engine-pgdata
  neo4j-data:
    driver: local
    name: bizinder-rag-engine-neo4j-data
  neo4j-logs:
    driver: local
    name: bizinder-rag-engine-neo4j-logs
  neo4j-import:
    driver: local
    name: bizinder-rag-engine-neo4j-import
  neo4j-plugins:
    driver: local
    name: bizinder-rag-engine-neo4j-plugins
  user_files:
    driver: local
    name: bizinder-rag-engine-user-files
